### ISSUE TITLE
Add a way to specify a background image in the welcome view

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#101]
For instance, for fourmilieres.net it could be an ant ;)

This could be specified in the configuration somehow.

**Comment by sahildua2305** [comment]
@almet I can pick it up. But will need some hint in getting started.

**Comment by almet** [comment]
Glad to hear that, @sahildua2305! I believe the way to do this would be by having the background image defined in the configuration, and having it picked-up in the `Welcome` module.

I've done that in the past and had problems with Webpack getting in the way, though, and I'm not enough fluent with it to solve the problem without more investigation. My guess is that it shouldn't be too complicated to solve ;-)

**Comment by almet** [comment]
I actually did a first version of it :-)

**Comment by sahildua2305** [comment]
Looks good! @almet 👍
