### ISSUE TITLE
Reduce the size of the generated bundle.js

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#102]
it's currently ~2MB!

Maybe @n1k0 would have some insights about it?

**Comment by n1k0** [comment]
WOW :D check that you're building using the `NODE_ENV=production` and that you're not bundling unused stuff.

**Comment by almet** [comment]
```$ ls -lah node_modules/slug/node_modules/unicode/category/So.js
-rw-rw-r-- 1 alexis alexis 1,8M févr.  3 22:13 node_modules/slug/node_modules/unicode/category/So.js
```

**Comment by n1k0** [comment]
Now that's a bold slug :D shouldn't be too hard to find another package or write your own function :)
