### ISSUE TITLE
Add a back button from the "form created" pannel

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#113]
Currently, the user needs to use the back button of the browser.

**Comment by Natim** [comment]
I don't know if the feature we want is to edit the created form or create a new one.
Using the back button will probably do the latter when I'd probably like to edit the form

**Comment by almet** [comment]
> Using the back button will probably do the latter when I'd probably like to edit the form

It's not the current behaviour: when using the back button you're presented the form you started creating.
