### ISSUE TITLE
Add the ability to save the jsonschema directly

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#115]

**Comment by rlecellier** [comment]
Actually it didnt work, i made a mistake using Link.

**Comment by lavish205** [comment]
@almet I would like to work on it, little guide to work on this will be very helpful.

**Comment by rlecellier** [comment]
It have been merged. I think we can close this issue.

**Comment by almet** [comment]
Thanks for the proposal @lavish205 anyway!
