### ISSUE TITLE
Add a noscript balise on the formbuilder page.

### ISSUE THREAD

**Issue by lanodan** [Kinto/formbuilder#120]
Could you use less javascript (at least loading everything but the interface) and/or put a message (when JS is disabled/not loaded) on why you use javascript.

**Comment by almet** [comment]
Hi, 

We made the decision to use Javascript as a hard requirement for this project. Especially  because everything is stored in an http database that needs to be requested from the browser. 

Displaying an error message when js is disabled is a good idea, maybe pointing to a question in the faq.

**Comment by lanodan** [comment]
I think adding why to the FAQ is a good idea so people wouldn’t have to dig in the issues.

**Comment by almet** [comment]
Fixed.
