### ISSUE TITLE
After having submited the form, the title doesn't change back to the homepage.

### ISSUE THREAD

**Issue by Natim** [Kinto/formbuilder#130]
When you open a form you have the title of the form, it doesn't change when you go back to the home page.

**Comment by Natim** [comment]
![example](https://cloud.githubusercontent.com/assets/229453/15935279/0b5ac82c-2e67-11e6-9ce5-daa97e018e7c.png)

**Comment by sahildua2305** [comment]
@Natim Do we want the `document.title` to change to `projectName` or `Formbuilder` after submitting?

**Comment by Natim** [comment]
Yes
