### ISSUE TITLE
Support for ALL react-jsonschema-form library types?

### ISSUE THREAD

**Issue by ramandhingra** [Kinto/formbuilder#139]
The Form Builder is based on the Mozilla Services react-jsonschema-form (rjsf) library. This library has a number of features/widgets like Arrays, Numbers, Date and Time, Ordering, Errors, etc. See here:
https://mozilla-services.github.io/react-jsonschema-form/

But in the Kinto Form Builder demo, there are only 4 widgets, namely, Short Text, Long Text, Check Box, Choice List. Is it possible to have all the widgets displayed supported by the react-jsonschema-form library? Also, how can I include the errors?

**Comment by Natim** [comment]
@ramandhingra That's something we'd like to do indeed. The problem is more about the UX to provide that than the JSONSchema rendering. Feel free to start to add the missing pieces if you want.

Note that it is also possible to upgrade the JSONSchema of the form using the kinto-admin project. That's how I force people to enter emails in some fields for instance.

**Comment by rlecellier** [comment]
I don't know which widget to add, if we add all the number (up-down, range, integer, float) widget the list will start to be huge.

**Comment by almet** [comment]
For sure we need to show the user a comprehensive list. If it's well sorted (with subsections) this should not be a problem.

**Comment by rlecellier** [comment]
i started to work on a other way to do it:
* left sidebar : text, number, date, one (string) of list, some (string) of list, ordered list
* editable field panel bar : 
 * text : short text - long text
 * number : number, number range,
 * date : date
 * one of list : radio buttons , select
 * some of list : checkboxes
 * ordered list : ordered 

Note that's the widget choices could also be on a extended sub menu of the sidebar. This may not be compatible with https://github.com/Kinto/formbuilder/pull/146

**Comment by almet** [comment]
I would prefer to only have one way to add a field. Otherwise this will clutter the overall UX.

**Comment by rlecellier** [comment]
The idea of the editable field's panel's header is not to add a new field but to switch from a widget to a other one when it's possible.
I choose a "one of list radio button's list", finaly i feel like a select is prettier. I double click on the field, choose the select widget on the header dropdown and save.

**Comment by almet** [comment]
Ah, okay, I understand now. I think this is a good idea. So we have two ways to interact with fields:

1. You add a field (currently from the left sidebar, but in the future with the "add a field" button;
2. You can change the specifics of the field you added (switch from short to long text for instance).

I think this makes perfect sense, let's go!
