### ISSUE TITLE
consulting help needed for mantra-react-form-builder

### ISSUE THREAD

**Issue by danutc** [Kinto/formbuilder#140]
Hi

We are developing a [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) based form builder specifically for [meteorjs](https://github.com/meteor/meteor) / [mantrajs](http://mantrajs.com/) / [mantra spec](https://github.com/kadirahq/mantra) / [mantra projects](https://github.com/mantrajs). We are looking for someone with Kinto formbuilder knowledge to help us.

Any help is highly appreciated.

**Comment by Natim** [comment]
Can you be more specific? Don't hesitate to join #kinto on IRC or [via Slack](https://slack.kinto-storage.org/)

**Comment by danutc** [comment]
@Natim I left private message on Slack. In a nutshell I need a consultant to assist developers who are on a learning curve with react-jsonschema-form  and Kinto formbuilder.

**Comment by almet** [comment]
This is not actionable for this project. closing.
