### ISSUE TITLE
Export CSV with multiline is broken

### ISSUE THREAD

**Issue by Natim** [Kinto/formbuilder#143]
If you have textarea and you try to export it as CSV, it create some line breaks in the CSV which breaks it.

**Comment by rlecellier** [comment]
I've juste test it, it work's perfecly well for me with 2 entries, a single line and a multi lines, for the same form's textarea.
I opened the csv file from a debian and a windows to check a possible issus about os line breaks. Clean csv for both case.

**Comment by Natim** [comment]
Also I discovered that the CSV encoding is confusing sometimes.

**Comment by almet** [comment]
Should we close this?
