### ISSUE TITLE
Switch field dropdown

### ISSUE THREAD

**Issue by rlecellier** [Kinto/formbuilder#153]
I still have some work to do but here a preview:

![screenshot from 2016-09-21 11-56-57](https://cloud.githubusercontent.com/assets/139848/18706652/315f675c-7ff3-11e6-90e0-3412e028ed98.png)
![screenshot from 2016-09-21 12-00-14](https://cloud.githubusercontent.com/assets/139848/18706653/31756480-7ff3-11e6-9ee8-7cc8d7868836.png)

**Comment by almet** [comment]
Now that's starting to look great :)

**Comment by rlecellier** [comment]
Pull request have been merged.
