### ISSUE TITLE
Frombuilder core & ui

### ISSUE THREAD

**Issue by rlecellier** [Kinto/formbuilder#155]
What about separate the ui part ? I know it's look's like big stuff.

The ui/components would be plug on core/container. We could have a ui-bootstrap and a ui-material as examples. 
This way anyone could plug the core formbuilder in any project design.

**Comment by almet** [comment]
I dont understand what would go where in this case? What do you consider the core?

**Comment by rlecellier** [comment]
I dont know realy, i just think that it may be possible to split apart the user interface.
I may try something then give news.

**Comment by rlecellier** [comment]
After making a proposal for this issus : #100 i've a update.
I still don't know how to split core and ux but here a explanation of why i thought about such thing:

Found a way get rid of bootstrap dependency in order to plug whatever css framework.
May be by a set of formbuilder's components and adapters that's extends bootstrap, marerial design, fondation or whatever components.

Theses _formbuilder's components and adapters_ would be the formbuilder ux, everything else would be the formbuilder core.

**Comment by rlecellier** [comment]
As we don't want to remove bootstrap dependency, this issus can be closed.
