### ISSUE TITLE
Improve Installation Docs

### ISSUE THREAD

**Issue by sahildua2305** [Kinto/formbuilder#163]
There is no mention of having `kinto` running in order to make this formbuilder work.

**Comment by rlecellier** [comment]
True, but the doc say : 
"SERVER_URL is the URL of the kinto server. It's default value depends on the environment that's being used (development, production, etc.)"

if you dont have a kinto server localy, you can found a host with a demo server easly on the kinto website.

**Comment by almet** [comment]
Thanks for reporting this. We can surely improve the documentation and state that you need a kinto server :)
