### ISSUE TITLE
Download as XLS

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#172]
_I've opened a series of issues more to start a discussion about certain features than to tell it should be done. This is one of them and we need to decide if we want to have it or not._

Downloading directly as XLS makes it easier to use for non-tech people (we currently support only CSV)

**Comment by sahildua2305** [comment]
@almet I'm working on this.

I'm using json2xls library but once I import it, I get this error - 
```javascript
Module not found: Error: Cannot resolve module 'fs' in /path/to/formbuilder/node_modules/json2xls/node_modules/excel-export
```

Have you faced such a problem?

**Comment by almet** [comment]
Yes, I think this module is outdated...

**Comment by sahildua2305** [comment]
@almet Do you know of another reliable module?

**Comment by almet** [comment]
I think we have to try some of them :-)

**Comment by sahildua2305** [comment]
I got json2xls working using a workaround. I will push it in some time.
