### ISSUE TITLE
Enable / disable form

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#173]
*I've opened a series of issues more to start a discussion about certain features than to tell it should be done. This is one of them and we need to decide if we want to have it or not.*

It should be possible to enable and disable the form (to accept new responses or not).

**Comment by almet** [comment]
I'm not sure how technically we should do this: we might want to add a new feature to kinto in order to support this. @leplatrem @Natim, do you have any thoughts about this?

**Comment by leplatrem** [comment]
Why not change the `record:create` permission?

**Comment by almet** [comment]
That is a good idea. Then we would need to read the permissions from the client and see if we have the right to publish or not. I hope these permissions will be readable :-)

**Comment by almet** [comment]
Duplicate of #114
