### ISSUE TITLE
Forms in several pages

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#180]
*I've opened a series of issues more to start a discussion about certain features than to tell it should be done. This is one of them and we need to decide if we want to have it or not.*

It could be useful for certain big forms to have the form split up in different pages.

**Comment by almet** [comment]
My personal opinion on this is that it's not really something useful. If we have really long forms, we should find better ways to navigate them than having multiple pages.

**Comment by rlecellier** [comment]
It's not rely important. But it give the user a nice way to design his form.
Depend of formbuilder's usage , it may be useful to bring the user step by step from simples questions to complex ones.

Thinking about this feature the other day, it could include a partial save of the form (page per page).
Also, in this "design your form" idea" we can also allow to add some html between fields (titles and paragraphs).

more digression: if we add a "confirmation mail" feature, it could be a page that'll partially save the form. Then the confirmation mail's link would target the second page of the form.

**Comment by almet** [comment]
I really do not think this would be useful for us here, and I believe we should keep our efforts on having a really easy to use product, without too nuch features that would bloat it.

In other terms, I think it means we need to implement the 20% of the features the people use 80% of their time, and I believe this is not one of them :)

**Comment by almet** [comment]
(Let me know if you disagree with this, I believe we need to trace a line between what we will and won't do, but I want to do it with the involved folks!)

**Comment by rlecellier** [comment]
Agree, this is something to do when the nothing else is missing. (never ?)
