### ISSUE TITLE
Prevent saving form when no field is added

### ISSUE THREAD

**Issue by sahildua2305** [Kinto/formbuilder#183]
As of now, if we save the form without adding any field, it will still save the empty form with no field.
Related to #181

**Comment by almet** [comment]
I would say it's a duplicate of it. Why do you think we should have the two issues open? How are they different?

**Comment by sahildua2305** [comment]
Now that I think of it, there is no difference. You're right. I'll close this one. Sorry!

**Comment by almet** [comment]
No worries :-)
