### ISSUE TITLE
Bug: Incorrect formatting in the downloaded CSV

### ISSUE THREAD

**Issue by sahildua2305** [Kinto/formbuilder#185]
This is the CSV downloaded:
<img width="434" alt="untitled_form__1_" src="https://cloud.githubusercontent.com/assets/5206277/19540566/be38104c-9660-11e6-944a-6c44af67a318.png">

And these were the responses for the form:
<img width="879" alt="formbuilder" src="https://cloud.githubusercontent.com/assets/5206277/19540585/e3cccdc0-9660-11e6-996d-49230ba26d55.png">

Not sure if there's actually something wrong or if I'm doing something wrong. Can someone please confirm?

**Comment by almet** [comment]
I believe you missed a step when opening the document: there is a prompt which asks you what the delimiter is, you might have entered the wrong one?

**Comment by sahildua2305** [comment]
I am on MacOS. It just opened the file, didn't ask for anything.

**Comment by almet** [comment]
Is this with Excel or something else?

**Comment by sahildua2305** [comment]
It's with MS Excel only.

**Comment by almet** [comment]
This is a regional thing, 

>To change comma to semicolon as the default Excel separator for CSV - go to Region -> Additional Settings -> Numbers tab -> List separator and type ; instead of the default ,
> — http://stackoverflow.com/questions/10140999/csv-with-comma-or-semicolon

I believe this will be fixed with the "export to xls" feature.

**Comment by sahildua2305** [comment]
Thanks for the link. But still I feel something is wrong with the fact that it shows first entry without quotes and the second one with quotes. Isn't that a thing to worry about?

**Comment by rlecellier** [comment]
@sahildua2305 what's the content of the file if you open it with a notepad ?

**Comment by almet** [comment]
#43 might solve this issue if it is related to a bad CSV file.

**Comment by almet** [comment]
Can you try https://github.com/Kinto/formbuilder/pull/189 and tell me if the bug still occurs?

**Comment by sahildua2305** [comment]
Looks good!

**Comment by sahildua2305** [comment]
Fixed via #189
