### ISSUE TITLE
demo bug ?

### ISSUE THREAD

**Issue by revolunet** [Kinto/formbuilder#194]
Hi here's a bug i got on the [demo app](https://kinto.github.io/formbuilder/) using chrome 54/Mac OS

Steps to reproduce :
 - Create a new form
 - Add a "select list"
 - Click submit -> nothing happens

<img width="543" alt="capture d ecran 2016-11-04 a 21 18 39" src="https://cloud.githubusercontent.com/assets/124937/20021101/a9b8352c-a2d4-11e6-91a4-5e2b88519d9e.png">

**Comment by almet** [comment]
Hi, thanks for the report. This is because this demo is not up to date and contains some bugs.
You can use https://www.fourmilieres.net instead in the meantime.

**Comment by almet** [comment]
I just fixed it, it should be all good on the demo github-pages branch. Thanks again for taking the time to help us figuring this out :)

**Comment by revolunet** [comment]
Thanks to YOU ! 👍
