### ISSUE TITLE
The url "https://www.fourmilieres.net" is on which branch?

### ISSUE THREAD

**Issue by JohnsonChee** [Kinto/formbuilder#198]
#I need to refer to the project of above url  ,please tell me the project is on which branch

**Comment by almet** [comment]
Hi, the deployed version is a snapshot at a given point in time. It is not on a specific branch. 

We should maybe use releases here to avoid any confusion.

**Comment by JohnsonChee** [comment]
your homepage 'https://www.fourmilieres.net' is different from your project that i cloned, though i think the  project present is more powerful, i still want to refer to the homepage's effect with drag and drop, can i have any access to that? (tips: my English is poor)

**Comment by almet** [comment]
You still can drag and drop the ui elements once they are in place. In order to go back to the "old" UI, you would need to use a commit before https://github.com/Kinto/formbuilder/commit/92dae6015a3d8ac62fa1138d0506e3dd5c90d0ad

You won't benefit, however from the changes we did since then.

**Comment by JohnsonChee** [comment]
Thanks~
