### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by marcelometal** [Kinto/formbuilder#207]
Hi!

Could you please add license file and the copyright holders?

Cheers!

**Comment by fabiofdsantos** [comment]
`Kinto and the formbuilder are released under Apache 2.0 licenses`

Source: https://kinto.github.io/formbuilder

**Comment by marcelometal** [comment]
Hi @fabiofdsantos thanks, but the license file should be present in the source repository (typically in the repo root) and not in the website.

@almet Could you please add a license file in the repository?

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by jhairau** [comment]
A license in the repository would ideal. I didn't look very hard, but I couldn't see licensing in the code files either.

Would you like me to create a PR for adding the license to the repo @fabiofdsantos, @almet ?

**Comment by almet** [comment]
This project is discontinued.
