### ISSUE TITLE
Order the fields during the listing of the results

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#22]

**Comment by n1k0** [comment]
Ordering data are available in the `uiSchema` object available from state, which should be posted to the collection data along the schema itself.

**Comment by almet** [comment]
Closing as [we're already doing it](http://github.com/Kinto/formbuilder/blob/c1ed111efa0336ef449b7b03744d5f0a3fed06b8/formbuilder/components/AdminView.js#L14)
