### ISSUE TITLE
Add widgets on simple click

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#35]
Currently it works using dragndrop. We should keep the dragndrop for the reorganisation of the widgets but we don't need to dragndrop them when they're first added.

**Comment by QuentinRoy** [comment]
I concur. Currently it seems that it is possible to add a widget by double-clicking on it in the selection pane. However I fail in understanding why a double click instead of a single one is required, and it is likely that many user won't ever discover this behaviour.
