### ISSUE TITLE
Add an edit button for the form label

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#38]
This can replace the "edit form property" link in the menu.

**Comment by QuentinRoy** [comment]
I concur. I encountered the issue myself.

**Comment by almet** [comment]
@natim thinks that we should display the user a first screen where he's forced to enter the name of the form, so that we won't create a lot of "untitled form" forms.

Another approach would be to add a small label next to the title saying "edit me!".

@QuentinRoy what do you think?

**Comment by QuentinRoy** [comment]
I tend to be careful when "user" and "force" are in the same sentence :).
A mix between the two could be to do as you say, and start the form creation in the edit mode of the text label.

**Comment by almet** [comment]
refs https://github.com/mozilla-services/react-jsonschema-form#custom-titles

**Comment by almet** [comment]
Fixed with https://github.com/Kinto/formbuilder/commit/f39bf3bae03471ffcd64237ac5c330b16354bdce, related to #64
