### ISSUE TITLE
Create an "Add a field" button + Publish the form

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#75]

**Comment by almet** [comment]
Adding some more context in this issue:

For a better UX, we could replace the menu on the left by an "add a field" button next to the "submit the form" one. Then it should be possible to change the added field type (but keep its title);

**Comment by rlecellier** [comment]
i started a branch on this issue. Here a result:

![screenshot add field dropdown](https://cloud.githubusercontent.com/assets/139848/18552932/e7a4797e-7b5e-11e6-8aab-751f7767fd1c.png)

My idea is to finalise the 'add field dropdown' on form's footer, then to add a 'change field dropdown' on editable field's head bar. 

To do it i used https://github.com/AllenFang/react-bootstrap-dropdown 
Is that acceptable to add this module in package.json ? 
if not, do you prefer a dedicated bootstrap dropdown for the formbuilder or a other premade module ?
if we decide to use react-bootstrap-dropdown, i'll add a iconClass property on it, the issus already exist.

**Comment by almet** [comment]
Yes that Is okay to add a dependency I suppose. Thanks for your work on this.

**Comment by rlecellier** [comment]
#146

**Comment by Natouille** [comment]
Good idea to drop the left menu for the add menu below.
But I am not sure **short text** and **long text** are clear denominations for the users.
I had to test it again to see what was behind. And I didn't see the difference. 
Can you explain please ?

**Comment by rlecellier** [comment]
The difference is on the result form, you'll have either a input that can contain one line or one that can contain several.
Google form use "short answer" / "paragraph" i may be better.
